# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/56d45875-d7d0-45d6-a959-91c7c74ac3f2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B428-0551";
      fsType = "vfat";
    };

#  fileSystems."/home" =
#    { device = "/dev/disk/by-uuid/9b890fa7-7c32-402d-8d65-843a2961c96e";
#      fsType = "ext4";
#    };

  # swapDevices =
  #   [ { device = "/dev/disk/by-uuid/19400e31-b22a-4c59-bcd8-2a23f61dd115"; }
  #   ];

  nix.maxJobs = lib.mkDefault 16;
  nix.buildCores = lib.mkDefault 16;
}
