# Do not modify this file!  It was generated by ‘nixos-generate-config’
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc"];
      kernelModules = ["dm-snapshot"];
      luks.devices."root" = {
        device = "/dev/disk/by-uuid/911c9598-6884-4f58-b665-5e44d30c4197";
        allowDiscards = true;
      };
    };
    kernelModules = ["kvm-amd" "sdhci" "sdhci_pci"];
    extraModulePackages = [];
    kernelParams = ["usbcore.autosuspend=-1"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ee717364-fe9d-4bc6-8666-0a4a0ab11091";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3B69-AFD3";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 16 * 1024;
    }
  ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
