{
  imports = [
    ./bundles/desktop.nix
    ./bundles/dev.nix
    ./bundles/extras.nix
    ./bundles/general.nix
    ./bundles/laptop.nix
    ./bundles/media.nix
    ./features/alacritty.nix
    ./features/env.nix
    ./features/git.nix
    ./features/hyprland.nix
    ./features/kitty.nix
    ./features/misc.nix
    ./features/nvf.nix
    ./features/shellAliases.nix
    ./features/waybar.nix
    ./features/wired.nix
    ./features/zsh.nix
  ];
}
