icons_format = "{icon}"

[theme]
theme = "slick"

[theme.overrides]
separator = ""

[icons]
icons = "awesome6"
[icons.overrides]
net_up = ""
net_down = ""
# net_up = "↑"
# net_down = "↓"

  # folder="$(mktemp -d)"
  # yq -i ".price.startup = $coinvalue" folder/btc.yaml
  # yq -i '.a.b[0].c = "cool"' btc.yaml
# [[block]]
# block = "custom"
# shell="bash"
# interval = 10
# command = '''
#   coinvalue="$(wget -q -O- https://api.binance.com/api/v3/ticker/price\?symbol\=BTCEUR | jq -r ".price | tonumber | floor")"
#   state="Idle"
#   if $(( coinvalue > 100000 )); then
#     state="Good"
#   elif $(( coinvalue < 96000 )); then
#     state="Info"
#   elif $(( coinvalue < 95000 )); then
#     state="Warning"
#   elif $(( coinvalue < 90000 )); then
#     state="Critical"
#   fi
#   echo "{\"state\":\"$state\", \"text\": \"$coinvalue\"}"
# '''
# format = "₿$text.pango-str()"
# json = true

# [[block]]
# block = "custom"
# shell="bash"
# interval = 10
# command = '''
#   coinvalue="$(wget -q -O- https://api.binance.com/api/v3/ticker/price\?symbol\=ETHEUR | jq -r ".price | tonumber | floor")"
#   state="Idle"
#   if $(( coinvalue > 4000 )); then
#     state="Good"
#   elif $(( coinvalue < 3400 )); then
#     state="Info"
#   elif $(( coinvalue < 3300 )); then
#     state="Warning"
#   elif $(( coinvalue < 3000 )); then
#     state="Critical"
#   fi
#   echo "{\"state\":\"$state\", \"text\": \"$coinvalue\"}"
# '''
# format = "⟠$text.pango-str()"
# json = true

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2)"

[[block]]
block = "memory"
format = "$mem_avail.eng(prefix:Gi)"
format_alt = "$swap_used_percents.eng(w:2)"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

#[[block]]
#block = "nvidia_gpu"
#label = ""
#show_utilization = false
#show_memory = true
#show_temperature = false
#interval = 1

[[block]]
block = "sound"
format = " $icon {$volume|}"
headphones_indicator = true

[[block]]
block = "sound"
device_kind = "source"
format = " $icon {$volume|}"

[[block]]
block = "net"
device = "enp2s0f0"
format = " $speed_down.eng(prefix:M)⇅$speed_up.eng(prefix:M)"
# format = "{ip}{graph_up;}{graph_down;}"
format_alt = " {ip}"
inactive_format = ""
missing_format = ""

# [[block]]
# block = "custom"
# command = '''if ! ping -W 10 -c 1 1.1.1.1 &> /dev/null; then echo "❌"; else echo "🟢"; fi'''
# format = "$text"
# interval = 15

[[block]]
block = "net"
device = "wlp3s0"
format = " $icon {$signal_strength|} $speed_down.eng(prefix:M)⇅$speed_up.eng(prefix:M)"
format_alt = " {ssid} {ip}"
interval = 5
inactive_format = ""
missing_format = ""

# [[block]]
# block = "time"
# interval = 5
# format = " $icon $timestamp.datetime(f:'%d/%m %R')"
# timezone = "Asia/Bangkok"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%R')"
timezone = "Europe/Berlin"

# block = "time"
# interval = 5
# format = "|%R"

