icons_format = "{icon}"

[theme]
theme = "slick"

[theme.overrides]
separator = ""

[icons]
icons = "awesome6"
[icons.overrides]
net_up = ""
net_down = ""
# net_up = "↑"
# net_down = "↓"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = "$icon $available.eng(w:2)"

[[block]]
block = "memory"
format = "$mem_avail.eng(prefix:Gi)"
format_alt = "$swap_used_percents.eng(w:2)"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

# [[block]]
# block = "load"
# interval = 1
# format = "{1m}"

#[[block]]
#block = "nvidia_gpu"
#label = ""
#show_utilization = false
#show_memory = true
#show_temperature = false
#interval = 1

[[block]]
block = "sound"
format = " $icon {$volume|}"
headphones_indicator = true

[[block]]
block = "sound"
device_kind = "source"
format = " $icon {$volume|}"

[[block]]
block = "net"
device = "enp2s0f0"
format = " $speed_down.eng(prefix:M)⇅$speed_up.eng(prefix:M)"
# format = "{ip}{graph_up;}{graph_down;}"
format_alt = " {ip}"
inactive_format = ""
missing_format = ""

[[block]]
block = "net"
device = "wlp3s0"
format = " $icon {$signal_strength|} $speed_down.eng(prefix:M)⇅$speed_up.eng(prefix:M)"
format_alt = " {ssid} {ip}"
interval = 5
inactive_format = ""
missing_format = ""

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(f:'%d/%m %R')"
