#!/bin/bash
killall conky
conky "$@" -p 1 -c /home/jelias/.conky/ConkyBar/configs/conky_bg &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_clock &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_txt &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_network &
#conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_banshee4 &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_system &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_cpu2 &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_ram &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_files &
# conky -c /home/jelias/.conky/ConkyBar/configs/conky_files2 &
conky "$@" -c /home/jelias/.conky/ConkyBar/configs/conky_weather &
exit
