addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
addSbtPlugin("com.softwaremill.clippy" % "plugin-sbt" % "0.6.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "2.0.0-RC6-1")
addSbtPlugin("io.get-coursier" % "sbt-pgp-coursier" % "2.0.0-RC6-1")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.1")
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.4.2")
addSbtPlugin("org.duhemm" % "sbt-errors-summary" % "0.6.3")
